apiVersion: 1
datasources:
  - id: 4
    uid: "client-infinity"
    orgId: 1
    name: "client"
    type: "yesoreyeram-infinity-datasource"
    url: "http://client:8002"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      customHealthCheckEnabled: true
      customHealthCheckUrl: "/health"
      global_queries: []
      pdcInjected: false
      refData: []
    readOnly: false
    apiVersion: ""
