apiVersion: 1
datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    editable: true
    version: 1
    basicAuth: false
    jsonData:
      timeInterval: "15s"